### =========================================
### API PLATOS - Backend Prisma + PostgreSQL
### Probando endpoints creados con:
### Express + Controller + Service + Prisma
### =========================================


### Obtener todos los platos
GET http://localhost:1500/api/platos

###


### Obtener un plato por ID
GET http://localhost:1500/api/platos/1

###


### Crear un nuevo plato
POST http://localhost:1500/api/platos
Content-Type: application/json

{
  "codigo": "BEB99",
  "nombre": "Cerveza Bien Fría",
  "descripcion": "Cerveza rubia helada servida en vaso congelado",
  "categoria": "BEBIDA",
  "precio": 4200,
  "tiempoPreparacion": 2
}

###